In [1]:
import numpy as np
import cat

In [7]:
#Demonstration inputs
X = np.random.randint(low = -5,  high = 5, size = (16, 1))
X = X.reshape((4, 4))
W = np.array([1, 2, 3, 4])
print(X)

[[ 3  4  0  0]
 [ 1  2  1 -5]
 [-1 -5 -3  3]
 [ 2  4  1 -5]]


In [3]:
#Input transformation for CAT
x_v = cat.transform_input(X)
x_v

array([ 2,  2, -2,  0,  0,  1,  3,  2,  2,  0,  4,  4, -2,  3, -1,  2])

In [4]:
#ReLU activation in CAT
Y = np.random.randint(low = -5, high = 5, size = (10, 1))
print("Y:", Y.T)
print("ReLU(Y):", cat.relu(Y).T)

Y: [[ 1 -2 -1 -4 -3  1  2  0 -2 -4]]
ReLU(Y): [[1. 0. 0. 0. 0. 1. 2. 0. 0. 0.]]


In [8]:
#Convolution Matrix in CAT
W_F = cat.conv_weights(W, X)
print("X:", X)
print("W:", W)
print("W_F:", W_F)

X: [[ 3  4  0  0]
 [ 1  2  1 -5]
 [-1 -5 -3  3]
 [ 2  4  1 -5]]
W: [1 2 3 4]
W_F: [[1. 2. 0. 0. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0. 0. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 3. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 2. 0. 0. 3. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 0. 0. 3. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 0. 0. 3. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 0. 0. 3. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 0. 0. 3. 4.]]


In [12]:
b = np.ones(W_F.shape[0])
x_v = cat.transform_input(X)
#cat.fully_connected(W_F, b, x_v)
print("Wx + b: ", np.matmul(W_F, x_v)+b)
print("ReLU(Wx + b): ", cat.fully_connected(W_F, b, x_v))

Wx + b:  [ 23.  15. -16. -17. -22.  -5.  12.   6. -13.]
ReLU(Wx + b):  [23. 15.  0.  0.  0.  0. 12.  6.  0.]
